feat: refactoring for tool-launcher
Проведён рефакторинг и стандартизирован режим отладки.

- -debug теперь показывает полезную информацию для всего кода
- улучшено оформление вывода
- ко многим функциям добавлена подробная документация
- мелкие улучшения и исправления логики внутри функций

tool-launcher: v1.2.0

diff --git a/tool-launcher b/tool-launcher
--- a/tool-launcher
+++ b/tool-launcher
@@ -3,10 +3,21 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-VERSION="1.1.1"
+VERSION="1.2.0"
 
-# Переменные для отладки
+# Режим отладки (включается при запуске с ключом '--debug' или '-d')
 unset DEBUG
+
+# Оформление вывода
+RED="\e[31m"
+GREEN="\e[32m"
+YELLOW="\e[33m"
+BLUE="\e[34m"
+BOLD="\e[1m"
+F_RESET="\e[0m"
+F_ERROR="[ ${RED}ERROR${F_RESET} ]"
+F_BLUE="${BOLD}${BLUE}::${F_RESET}"
+F_GREEN="${BOLD}${GREEN}::${F_RESET}"
 
 # Список терминалов для проверки.
 # Используется в случае, если не получилось определить терминал по умолчанию.
@@ -21,9 +32,8 @@ DEFAULT_TERMINALS=(
 )
 
 
-# === Функции ===
+# === Вспомогательные функции ===
 
-# Отображает справку по использованию скрипта
 show_help() {
   cat <<EOF
 Tool Launcher — универсальный менеджер установки и запуска утилит.
@@ -39,12 +49,9 @@ Tool Launcher — универсальный менеджер установки
 
 
 Опции:
-  -h, --help      Показать эту справку и выйти
-  -v, --version   Показать версию скрипта
-  -d, --debug     Запуск скрипта в режиме отладки:
-                    - определение DE
-                    - определение терминала по умолчанию
-                    - запуск основного скрипта в новом окне найденного терминала
+  -h, --help       Показать эту справку
+  -v, --version    Показать версию скрипта
+  -d, --debug      Запуск в режиме отладки
 
 Примеры:
   ./$(basename "$0")
@@ -53,10 +60,32 @@ Tool Launcher — универсальный менеджер установки
 EOF
 }
 
-# Инициализация окружения
+show_hello() {
+  cat <<EOF
+:::::::::::::::::::::::
+:::: Tool Launcher ::::
+:::::::::::::::: v${VERSION}
+
+EOF
+}
+
+# === Вывод отладочной информации ===
+# -----------------------------------
+# Работает только в случае, если скрипт запущен в режиме отладки,
+# то есть с флагами -d или --debug
+#
+# Использование: log_debug "Сообщение"
+# -----------------------------------
+log_debug() {
+  if [[ -v DEBUG ]]; then
+    echo -e "[ ${YELLOW}DEBUG${F_RESET} ] $*" >&2
+  fi
+}
+
+# === Инициализация окружения ===
 init_env() {
   if ! command -v git >/dev/null 2>&1; then
-    echo "Ошибка: не найден git. Установите его, чтобы использовать этот скрипт." >&2
+    echo -e "${F_ERROR} Не найден git. Установите его, чтобы использовать этот скрипт." >&2
     exit 1
   fi
 
@@ -65,209 +94,175 @@ init_env() {
 
   # Хранит название конфигурации из .gitmodules для использования
   REPO_TOOLS_NAME="tools"
-
   REPO_ROOT="$(git -C "$MAIN_PATH" rev-parse --show-toplevel)"
   TARGET_SCRIPT="${REPO_ROOT}/tools/start"
-
   DE=""
-}
 
-# Обновляет сабмодуль до актуального состояния
-#   $1 — название сабмодуля из конфигурации .gitmodules (обязательно)
-update_submodule() {
-  if [[ $# -ne 1 ]]; then
-    echo "Ошибка: update_submodule() требует 1 аргумент — путь до сабмодуля." >&2
-    return 1
-  fi
-  local submodule_name=$1
-
-  echo ":: Проверка и обновление сабмодуля '$submodule_name'..."
-
-  if ! git submodule update --init --remote -- "$submodule_name"; then
-    echo "Ошибка: Не удалось обновить сабмодуль '$submodule_name'." >&2
-    return 1
-  fi
-
-  echo ":: Сабмодуль успешно обновлен или уже актуален."
-}
-
-# Запускает указанный скрипт в новом окне терминала
-#   $1 — путь до исполняемого файла (обязательно)
-run_in_terminal() {
-  if [[ $# -ne 1 ]]; then
-    echo "Ошибка: run_in_terminal() требует 1 аргумент — путь до скрипта." >&2
-    return 1
-  fi
-  local path_to_script=$1
-  local terminal
-
-  if [[ ! -f "$path_to_script" ]]; then
-    echo "Ошибка: Файл '$path_to_script' не существует." >&2
-    return 1
-  fi
-
-  terminal=$(find_terminal)
-  if [[ -z "$terminal" ]]; then
-    echo "Ошибка: Не удалось найти поддерживаемый эмулятор терминала." >&2
-    exit 1
-  fi
-  echo ":: Запуск '$path_to_script' в новом окне ($terminal)..."
-
-  # Применяет правильный ключ в зависимости от терминала
-  case "$terminal" in
-    terminator|xfce4-terminal)
-      "$terminal" -x "$path_to_script"
-      ;;
-    gnome-terminal|kitty)
-      "$terminal" -- "$path_to_script"
-      ;;
-    *) "$terminal" -e "$path_to_script" ;;
-  esac
+  log_debug "Рабочая директория: $MAIN_PATH"
+  log_debug "Целевой скрипт: $TARGET_SCRIPT"
 }
 
 
-# --- Определение DE ---
+# === Функции определения DE ===
+# ------------------------------
+# Поддерживаются:
+#   - KDE Plasma
+#   - GNOME
+#   - XFCE
+# ------------------------------
 
-# Проверяет, запущена ли текущая сессия KDE Plasma
 is_kde() {
-  # Проверяем по переменным окружения и процессам
-  [[ "${XDG_CURRENT_DESKTOP:-}" == *"KDE"* ]] ||
-  [[ "${DESKTOP_SESSION:-}" == "plasma" ]] ||
-  [[ "${KDE_FULL_SESSION:-}" == "true" ]] ||
-  pgrep -x "plasmashell" >/dev/null 2>&1
+  if [[ "${XDG_CURRENT_DESKTOP:-}" == *"KDE"* ]] ||
+    [[ "${DESKTOP_SESSION:-}" == "plasma" ]] ||
+    [[ "${KDE_FULL_SESSION:-}" == "true" ]] ||
+    pgrep -x "plasmashell" >/dev/null 2>&1; then
+    DE="KDE Plasma"
+    log_debug "Обнаружено окружение: ${BOLD}${DE}${F_RESET}"
+    return 0
+  fi
+  return 1
 }
 
-# Проверяет, запущена ли текущая сессия GNOME или совместимая с ним
 is_gnome() {
   local desktop_env="${XDG_CURRENT_DESKTOP:-}"
 
-  # Проверяет основные маркеры GNOME и MATE (который использует схожие технологии)
-  [[ "$desktop_env" == *"GNOME"* ]] ||
-  [[ "$desktop_env" == *"MATE"* ]] ||
-  [[ "${DESKTOP_SESSION:-}" == "gnome" ]] ||
-  pgrep -x "gnome-shell" >/dev/null 2>&1
+  if [[ "$desktop_env" == *"GNOME"* ]] ||
+    [[ "$desktop_env" == *"MATE"* ]] ||
+    [[ "${DESKTOP_SESSION:-}" == "gnome" ]] ||
+    pgrep -x "gnome-shell" >/dev/null 2>&1; then
+    DE="GNOME"
+    log_debug "Обнаружено окружение: ${BOLD}${DE}${F_RESET}"
+    return 0
+  fi
+  return 1
 }
 
-# Проверяет, запущена ли текущая сессия XFCE
 is_xfce() {
-  [[ "${XDG_CURRENT_DESKTOP:-}" == *"XFCE"* ]] ||
-  [[ "${DESKTOP_SESSION:-}" == "xfce" ]] ||
-  pgrep -fx "xfce4-session" >/dev/null 2>&1
+  if [[ "${XDG_CURRENT_DESKTOP:-}" == *"XFCE"* ]] ||
+    [[ "${DESKTOP_SESSION:-}" == "xfce" ]] ||
+    pgrep -fx "xfce4-session" >/dev/null 2>&1; then
+    DE="XFCE"
+    log_debug "Обнаружено окружение: ${BOLD}${DE}${F_RESET}"
+    return 0
+  fi
+  return 1
 }
 
 
-# --- Поиск терминала по умолчанию в DE ---
+# === Вспомогательные функции поиска терминала ===
+# ------------------------------------------------
+# Каждая из функций  пытается найти терминал по умолчанию в своём DE.
+#
+# Возвращает: путь до установленного пользователем терминала по умолчанию
+#             или путь до дефолтного терминала.
+# ------------------------------------------------
 
-# Ищет в KDE терминал по умолчанию и возвращает путь до его бинарника
 get_kde_default_terminal() {
-  local term_bin
+  local term_bin kconfig_cmd
 
   if command -v kreadconfig6 >/dev/null 2>&1; then
-
-  if [[ -v DEBUG ]]; then
-    echo ">>> Найдена утилита 'kreadconfig6'" >&2
+    kconfig_cmd="kreadconfig6"
+  elif command -v kreadconfig5 >/dev/null 2>&1; then
+    kconfig_cmd="kreadconfig5"
   fi
 
-    term_bin="$(kreadconfig6 --file kdeglobals --group General --key TerminalApplication)"
+  if [[ -n "$kconfig_cmd" ]]; then
+    log_debug "Чтение конфига ${DE} через ${BOLD}$kconfig_cmd${F_RESET}..."
+    term_bin="$($kconfig_cmd --file kdeglobals --group General --key TerminalApplication)"
+
     if [[ -n "$term_bin" ]]; then
-
-      if [[ -v DEBUG ]]; then
-        echo -e ">>> Найден терминал: ${term_bin}" >&2
-      fi
-
+      log_debug "Конфигурация вернула: ${GREEN}$term_bin${F_RESET}"
       echo "$term_bin"
       return 0
+    else
+      log_debug "Ключ TerminalApplication пуст или не найден."
     fi
+  else
+    log_debug "Утилиты kreadconfig не найдены."
   fi
 
-  # Если ничего не найдено, возвращаем дефолт KDE
+  # Попытка вернуть дефолт для KDE
   if term_bin=$(command -v konsole) && [[ -n "$term_bin" ]]; then
+    log_debug "Возврат дефолтного терминала для ${DE}"
     echo "$term_bin"
     return 0
   fi
 
-  # Если совсем ничего не нашли (крайний случай)
-  echo -e "Ошибка: не удалось определить терминал для {$DE}" >&2
+  echo -e "${F_ERROR} не удалось определить терминал для {$DE}" >&2
   return 1
 }
 
-# Ищет в GNOME/Gnome-совместимых DE терминал по умолчанию
 get_gnome_default_terminal() {
   local term_bin
 
   if command -v gsettings >/dev/null 2>&1; then
-    # Ключ, который указывает на команду, используемую для запуска терминала
-    # (например, 'gnome-terminal', 'tilix' и т.д.)
+    log_debug "Запрос 'gsettings get ...'"
     term_bin="$(gsettings get org.gnome.desktop.applications terminal exec 2>/dev/null)"
-
-    # gsettings возвращает строку в одинарных кавычках, их нужно убрать
-    term_bin="${term_bin//\'/}"
+    term_bin="${term_bin//\'/}"  # Удаление кавычек
 
     if [[ -n "$term_bin" ]]; then
       if command -v "$term_bin" &>/dev/null; then
+        log_debug "gsettings вернул: ${GREEN}$term_bin${F_RESET}"
         echo "$term_bin"
         return 0
       fi
     fi
+  else
+    log_debug "Утилита gsettings не найдена."
   fi
 
-  # Если gsettings не сработал или не дал результата, 
-  # возвращаем дефолт GNOME, если он установлен
+  # Попытка вернуть дефолт для GNOME
   if term_bin=$(command -v gnome-terminal) && [[ -n "$term_bin" ]]; then
+    log_debug "Возврат дефолтного терминала для ${DE}"
     echo "$term_bin"
     return 0
   fi
 
-  # Если совсем ничего не нашли (крайний случай)
   echo -e "Ошибка: не удалось определить терминал для {$DE}" >&2
   return 1
 }
 
-# Ищет терминал по умолчанию в XFCE
 get_xfce_default_terminal() {
   local config_file="$HOME/.config/xfce4/helpers.rc"
   local term_bin
 
   # XFCE хранит настройки приложений по умолчанию (через exo) в helpers.rc
   if [[ -f "$config_file" ]]; then
-    # Ищем строку вида TerminalEmulator=название
+    log_debug "Чтение файла: $config_file"
     term_bin=$(grep "^TerminalEmulator=" "$config_file" | cut -d'=' -f2)
-
-    if [[ -v DEBUG ]]; then
-      echo -e ">>> Произведён поиск в директории: ${config_file}" >&2
-      echo -e ">>> Значение 'TerminalEmulator': ${term_bin}" >&2
-    fi
+    log_debug "Найдено значение TerminalEmulator: ${GREEN}$term_bin${F_RESET}"
+  else
+    log_debug "Файл конфигурации $config_file не найден."
   fi
 
-  # ПРОВЕРКА 1: Если нашли настройку и она является валидной командой
+  # Проверка значения из 'helpers.rc'
   if [[ -n "$term_bin" ]] && command -v "$term_bin" >/dev/null 2>&1; then
+    log_debug "'helpers.rc' вернул: ${GREEN}$term_bin${F_RESET}"
     echo "$term_bin"
     return 0
-  fi
-
-  # ПРОВЕРКА 2: Обработка "Custom" (пользовательских) терминалов
-  # Если в конфиге написано "custom-TerminalEmulator", нужно искать в локальных хелперах
-  if [[ "$term_bin" == "custom-TerminalEmulator" ]]; then
+  # Или 'custom-TerminalEmulator.desktop'
+  elif [[ "$term_bin" == "custom-TerminalEmulator" ]]; then
     local custom_helper="$HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop"
+
+    log_debug "Обнаружен custom-TerminalEmulator, проверяем: $custom_helper"
+
     if [[ -f "$custom_helper" ]]; then
-      # Извлекаем команду из .desktop файла (строка Bin=...)
-      term_bin=$(grep "^Bin=" "$custom_helper" | cut -d'=' -f2 | awk '{print $1}')
+      local custom_cmd
 
-      if [[ -v DEBUG ]]; then
-        echo -e ">>> Произведён поиск в директории: ${custom_helper}" >&2
-        echo -e ">>> Значение 'custom-TerminalEmulator': ${term_bin}" >&2
-      fi
+      custom_cmd=$(grep "^Bin=" "$custom_helper" | cut -d'=' -f2 | awk '{print $1}')
+      log_debug "Извлечена команда из desktop-файла: $custom_cmd"
 
-      if command -v "$term_bin" >/dev/null 2>&1; then
-        echo "$term_bin"
+      if [[ -n "$custom_cmd" ]] && command -v "$custom_cmd" >/dev/null 2>&1; then
+        log_debug "'custom-TerminalEmulator.desktop' вернул: ${GREEN}$custom_cmd${F_RESET}"
+        echo "$custom_cmd"
         return 0
       fi
     fi
   fi
 
-  # ПРОВЕРКА 3 (Fallback): Если настройка не найдена или команда невалидна,
-  # проверяем наличие стандартного xfce4-terminal
+  # Попытка вернуть дефолт для XFCE
   if term_bin=$(command -v xfce4-terminal) && [[ -n "$term_bin" ]]; then
+    log_debug "Возврат дефолтного терминала для ${DE}"
     echo "$term_bin"
     return 0
   fi
@@ -278,61 +273,40 @@ get_xfce_default_terminal() {
 }
 
 
-# --- Основная логика поиска ---
-
-# Ищет терминал, в котором можно запустить скрипт в новом окне
+# === Главная функция поиска терминала ===
+# ----------------------------------------
+# Ищет терминал, подходящий для запуска основного скрипта в новом окне.
+#
+# Проверяет, поддерживается ли DE пользователя.
+#   Если да: ищет терминал по умолчанию для DE.
+#   Если нет: ищет в списке поддерживаемых терминалов.
+#
+# Возвращает: путь до бинарника терминала.
+# ----------------------------------------
 find_terminal() {
   local terminal
 
-  # Ищем терминал в KDE приложениях по умолчанию
+  # Попытка определить через DE
   if is_kde; then
-    DE="KDE"
-
-    if [[ -v DEBUG ]]; then
-      echo -e ">>> Используемое DE: {$DE}" >&2
-    fi
-
     terminal="$(get_kde_default_terminal)"
-
-    if [[ -n "$terminal" ]]; then
-      echo "$terminal"
-      return 0
-    fi
-  fi
-
-  # Ищем терминал в GNOME приложениях по умолчанию
-  if is_gnome; then
-    DE="GNOME"
-
-    if [[ -v DEBUG ]]; then
-      echo -e ">>> Используемое DE: {$DE}" >&2
-    fi
-
+  elif is_gnome; then
     terminal="$(get_gnome_default_terminal)"
-    if [[ -n "$terminal" ]]; then
-      echo "$terminal"
-      return 0
-    fi
-  fi
-
-  # Ищем терминал в GNOME приложениях по умолчанию
-  if is_xfce; then
-    DE="XFCE"
-
-    if [[ -v DEBUG ]]; then
-      echo -e ">>> Используемое DE: {$DE}" >&2
-    fi
-
+  elif is_xfce; then
     terminal="$(get_xfce_default_terminal)"
-    if [[ -n "$terminal" ]]; then
-      echo "$terminal"
-      return 0
-    fi
   fi
+
+  if [[ -n "$terminal" ]]; then
+    log_debug "Для ${DE} используется терминал: ${BOLD}$terminal${F_RESET}"
+    echo "$terminal"
+    return 0
+  fi
+
+  log_debug "Не удалось определить DE или терминал для него. Перебор списка по умолчанию..."
 
   # Если DE пользователя не поддерживается
   for terminal in "${DEFAULT_TERMINALS[@]}"; do
     if command -v "$terminal" &>/dev/null; then
+      log_debug "Найден терминал из списка: ${BOLD}$terminal${F_RESET}"
       echo "$terminal"
       return 0
     fi
@@ -341,32 +315,107 @@ find_terminal() {
   return 1
 }
 
+# === Запуск скрипта в новом окне терминала ===
+# ---------------------------------------------
+# Запускает указанный скрипт в новом окне терминала
+#   $1 — путь до исполняемого файла (обязательно)
+# ---------------------------------------------
+run_in_terminal() {
+  if [[ $# -ne 1 ]]; then
+    echo -e "${F_ERROR} 'run_in_terminal()' требует 1 аргумент — путь до скрипта." >&2
+    return 1
+  fi
+  local path_to_script=$1
+  local terminal
+  local args=()
+
+  if [[ ! -f "$path_to_script" ]]; then
+    echo -e "${F_ERROR} Файл '$path_to_script' не существует." >&2
+    return 1
+  fi
+
+  terminal=$(find_terminal)
+  if [[ -z "$terminal" ]]; then
+    echo -e "${F_ERROR} Не удалось найти поддерживаемый эмулятор терминала." >&2
+    exit 1
+  fi
+
+  echo -e "${F_GREEN} Запуск '$path_to_script' в новом окне ($terminal)..."
+
+  # Применяет правильный ключ в зависимости от терминала
+  case "$terminal" in
+    terminator|xfce4-terminal)
+      args=("-x" "$path_to_script")
+      ;;
+    gnome-terminal|gnome-console|kitty)
+      args=("--" "$path_to_script")
+      ;;
+    *)
+      # Стандартный вариант запуска
+      args=("-e" "$path_to_script")
+      ;;
+  esac
+
+  log_debug "Выполняется команда: ${BOLD}$terminal ${args[*]}${F_RESET}"
+
+  # Запуск
+  "$terminal" "${args[@]}"
+}
+
+
+# === Работа с сабмодулем ===
+# ---------------------------
+# Обновляет сабмодуль до актуального состояния
+#   $1 — название сабмодуля из конфигурации .gitmodules (обязательно)
+# ---------------------------
+update_submodule() {
+  if [[ $# -ne 1 ]]; then
+    echo "${F_ERROR} 'update_submodule()' требует 1 аргумент — путь до сабмодуля." >&2
+    return 1
+  fi
+  local submodule_name=$1
+
+  echo -e "${F_BLUE} Проверка и обновление сабмодуля ${BOLD}'$submodule_name'${F_RESET}..."
+
+  if ! git submodule update --init --remote -- "$submodule_name"; then
+    echo "Ошибка: Не удалось обновить сабмодуль '$submodule_name'." >&2
+    return 1
+  fi
+
+  echo -e "${F_GREEN} ${GREEN}Сабмодуль успешно обновлен или уже актуален${F_RESET}"
+}
+
 
 # === Основная логика ===
-
+# -----------------------
+# - обрабатывает полученные при запуске ключи
+# - выводит информацию о скрипте
+# - устанавливает окружение (переменные)
+# - обновляет сабмодуль
+# - запускает целевой скрипт из сабмодуля или ищет терминал для запуска в окне
+# -----------------------
 
 # --- Обработка вариантов запуска с ключами ---
-
 case "${1:-}" in
   -h|--help) show_help; exit 0 ;;
-  -v|--version) echo "${VERSION}"; exit 0 ;;
+  -v|--version) echo "v${VERSION}"; exit 0 ;;
   -d|--debug) DEBUG=1 ;;
   -*)
-    echo "Неизвестная опция: $1" >&2
-    echo "Используйте --help для справки." >&2
+    echo "Неизвестная опция: $1. Используйте --help для справки." >&2
     exit 1
     ;;
 esac
 
 
-# --- Запуск ---
+# === Запуск ===
 
+show_hello
 init_env
 update_submodule "$REPO_TOOLS_NAME"
 
 
 if [[ -v DEBUG ]]; then
-  echo ">>> Запуск скрипта в режиме отладки..."
+  log_debug "${BLUE}Запуск в режиме отладки${F_RESET} (открытие нового окна принудительно)"
   run_in_terminal "$TARGET_SCRIPT"
   exit 0
 fi
@@ -374,7 +423,7 @@ fi
 # Если код выполняется в окне терминала, то запустит следующий скрипт в нём
 # Иначе: запустит скрипт в новом окне терминала
 if test -t 0; then
-  echo ":: Запуск интерактивного меню..."
+  echo -e "${F_GREEN} Запуск интерактивного меню..."
   $TARGET_SCRIPT
 else
   run_in_terminal "$TARGET_SCRIPT"
